// <auto-generated />
using System;
using FiscalFlow.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiscalFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106191931_CreateSatCatalogs")]
    partial class CreateSatCatalogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiscalFlow.Domain.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Logs");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("FiscalFlow.Domain.AuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__AuthToke__3214EC079412461B");

                    b.HasIndex("UserId");

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("FiscalFlow.Domain.BatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CfdiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__BatchIte__3214EC07B445316F");

                    b.HasIndex("BatchId");

                    b.HasIndex("CfdiId");

                    b.ToTable("BatchItems");
                });

            modelBuilder.Entity("FiscalFlow.Domain.Certificate", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("CerFile")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CertificateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<byte[]>("EncryptedKeyPassword")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("KeyFile")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("CertificateId")
                        .HasName("PK__Certific__BBF8A7C1EB9B1929");

                    b.HasIndex("UserId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("FiscalFlow.Domain.Cfdi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RfcEmisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RfcReceptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Cfdi__3214EC07C9F4101B");

                    b.HasIndex("UserId");

                    b.ToTable("Cfdis");
                });

            modelBuilder.Entity("FiscalFlow.Domain.CfdiBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__CfdiBatc__3214EC075B40917A");

                    b.HasIndex("UserId");

                    b.ToTable("CfdiBatches");
                });

            modelBuilder.Entity("FiscalFlow.Domain.CfdiPdf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CfdiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CfdiPdf__3214EC077BD0039A");

                    b.HasIndex("CfdiId");

                    b.ToTable("CfdiPdfs");
                });

            modelBuilder.Entity("FiscalFlow.Domain.CfdiStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CfdiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__CfdiStat__3214EC07806CC8C9");

                    b.HasIndex("CfdiId");

                    b.ToTable("CfdiStatusHistories");
                });

            modelBuilder.Entity("FiscalFlow.Domain.CfdiXml", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CfdiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("XmlContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__CfdiXml__D14A66895961B32B");

                    b.HasIndex("CfdiId");

                    b.ToTable("CfdiXmls");
                });

            modelBuilder.Entity("FiscalFlow.Domain.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CfdiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__EmailLog__3214EC0787196443");

                    b.HasIndex("CfdiId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("FiscalFlow.Domain.Entities.SatCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CfdiVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SatCatalog", (string)null);
                });

            modelBuilder.Entity("FiscalFlow.Domain.Entities.SatCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SatCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SatCatalogId", "KeyCode")
                        .IsUnique();

                    b.HasIndex("KeyCode", "StartDate", "EndDate");

                    b.ToTable("SatCatalogItem", (string)null);
                });

            modelBuilder.Entity("FiscalFlow.Domain.Entities.SatCatalogRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppliesToCatalog")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AppliesToKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CatalogCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogCode", "ItemKey", "AppliesToCatalog", "AppliesToKey");

                    b.ToTable("SatCatalogRule", (string)null);
                });

            modelBuilder.Entity("FiscalFlow.Domain.ErrorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id")
                        .HasName("PK_LogError");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("FiscalFlow.Domain.MassDownloadFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__MassDown__3214EC073AFD2AE7");

                    b.HasIndex("RequestId");

                    b.ToTable("MassDownloadFiles");
                });

            modelBuilder.Entity("FiscalFlow.Domain.MassDownloadRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__MassDown__3214EC07A2F80CC1");

                    b.HasIndex("UserId");

                    b.ToTable("MassDownloadRequests");
                });

            modelBuilder.Entity("FiscalFlow.Domain.StampBalance", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableStamps")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("UserId")
                        .HasName("PK__StampBal__1788CC4C7B76C78B");

                    b.ToTable("StampBalances");
                });

            modelBuilder.Entity("FiscalFlow.Domain.StampMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("CfdiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__StampMov__3214EC07292A7110");

                    b.HasIndex("CfdiId");

                    b.HasIndex("UserId");

                    b.ToTable("StampMovements");
                });

            modelBuilder.Entity("FiscalFlow.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC075204049E");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FiscalFlow.Domain.ActivityLog", b =>
                {
                    b.HasOne("FiscalFlow.Domain.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Logs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiscalFlow.Domain.AuthToken", b =>
                {
                    b.HasOne("FiscalFlow.Domain.User", "User")
                        .WithMany("AuthTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AuthToken__UserI__3E52440B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiscalFlow.Domain.BatchItem", b =>
                {
                    b.HasOne("FiscalFlow.Domain.CfdiBatch", "Batch")
                        .WithMany("BatchItems")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK__BatchItem__Batch__6A30C649");

                    b.HasOne("FiscalFlow.Domain.Cfdi", "Cfdi")
                        .WithMany("BatchItems")
                        .HasForeignKey("CfdiId")
                        .IsRequired()
                        .HasConstraintName("FK__BatchItem__CfdiI__6B24EA82");

                    b.Navigation("Batch");

                    b.Navigation("Cfdi");
                });

            modelBuilder.Entity("FiscalFlow.Domain.Certificate", b =>
                {
                    b.HasOne("FiscalFlow.Domain.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Certifica__UserI__08B54D69");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiscalFlow.Domain.Cfdi", b =>
                {
                    b.HasOne("FiscalFlow.Domain.User", "User")
                        .WithMany("Cfdis")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Cfdi__UserId__49C3F6B7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiscalFlow.Domain.CfdiBatch", b =>
                {
                    b.HasOne("FiscalFlow.Domain.User", "User")
                        .WithMany("CfdiBatches")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CfdiBatch__UserI__66603565");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiscalFlow.Domain.CfdiPdf", b =>
                {
                    b.HasOne("FiscalFlow.Domain.Cfdi", "Cfdi")
                        .WithMany("CfdiPdfs")
                        .HasForeignKey("CfdiId")
                        .IsRequired()
                        .HasConstraintName("FK__CfdiPdf__CfdiId__5812160E");

                    b.Navigation("Cfdi");
                });

            modelBuilder.Entity("FiscalFlow.Domain.CfdiStatusHistory", b =>
                {
                    b.HasOne("FiscalFlow.Domain.Cfdi", "Cfdi")
                        .WithMany("CfdiStatusHistories")
                        .HasForeignKey("CfdiId")
                        .IsRequired()
                        .HasConstraintName("FK__CfdiStatu__CfdiI__4E88ABD4");

                    b.Navigation("Cfdi");
                });

            modelBuilder.Entity("FiscalFlow.Domain.CfdiXml", b =>
                {
                    b.HasOne("FiscalFlow.Domain.Cfdi", "Cfdi")
                        .WithMany("CfdiXmls")
                        .HasForeignKey("CfdiId")
                        .IsRequired()
                        .HasConstraintName("FK__CfdiXml__CfdiId__534D60F1");

                    b.Navigation("Cfdi");
                });

            modelBuilder.Entity("FiscalFlow.Domain.EmailLog", b =>
                {
                    b.HasOne("FiscalFlow.Domain.Cfdi", "Cfdi")
                        .WithMany("EmailLogs")
                        .HasForeignKey("CfdiId")
                        .IsRequired()
                        .HasConstraintName("FK__EmailLog__CfdiId__6FE99F9F");

                    b.Navigation("Cfdi");
                });

            modelBuilder.Entity("FiscalFlow.Domain.Entities.SatCatalogItem", b =>
                {
                    b.HasOne("FiscalFlow.Domain.Entities.SatCatalog", "Catalog")
                        .WithMany("Items")
                        .HasForeignKey("SatCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("FiscalFlow.Domain.MassDownloadFile", b =>
                {
                    b.HasOne("FiscalFlow.Domain.MassDownloadRequest", "Request")
                        .WithMany("MassDownloadFiles")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__MassDownl__Reque__787EE5A0");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FiscalFlow.Domain.MassDownloadRequest", b =>
                {
                    b.HasOne("FiscalFlow.Domain.User", "User")
                        .WithMany("MassDownloadRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__MassDownl__UserI__74AE54BC");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiscalFlow.Domain.StampBalance", b =>
                {
                    b.HasOne("FiscalFlow.Domain.User", "User")
                        .WithOne("StampBalance")
                        .HasForeignKey("FiscalFlow.Domain.StampBalance", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__StampBala__UserI__5BE2A6F2");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiscalFlow.Domain.StampMovement", b =>
                {
                    b.HasOne("FiscalFlow.Domain.Cfdi", "Cfdi")
                        .WithMany("StampMovements")
                        .HasForeignKey("CfdiId")
                        .HasConstraintName("FK__StampMove__CfdiI__619B8048");

                    b.HasOne("FiscalFlow.Domain.User", "User")
                        .WithMany("StampMovements")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__StampMove__UserI__60A75C0F");

                    b.Navigation("Cfdi");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiscalFlow.Domain.Cfdi", b =>
                {
                    b.Navigation("BatchItems");

                    b.Navigation("CfdiPdfs");

                    b.Navigation("CfdiStatusHistories");

                    b.Navigation("CfdiXmls");

                    b.Navigation("EmailLogs");

                    b.Navigation("StampMovements");
                });

            modelBuilder.Entity("FiscalFlow.Domain.CfdiBatch", b =>
                {
                    b.Navigation("BatchItems");
                });

            modelBuilder.Entity("FiscalFlow.Domain.Entities.SatCatalog", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FiscalFlow.Domain.MassDownloadRequest", b =>
                {
                    b.Navigation("MassDownloadFiles");
                });

            modelBuilder.Entity("FiscalFlow.Domain.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("AuthTokens");

                    b.Navigation("Certificates");

                    b.Navigation("CfdiBatches");

                    b.Navigation("Cfdis");

                    b.Navigation("MassDownloadRequests");

                    b.Navigation("StampBalance");

                    b.Navigation("StampMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
