//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiscalFlow.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiscalFlow.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El certificado del emisor ha sido revocado..
        /// </summary>
        internal static string CertificateRevoked {
            get {
                return ResourceManager.GetString("CertificateRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comprobante ya fue timbrado previamente..
        /// </summary>
        internal static string DuplicateCfdi {
            get {
                return ResourceManager.GetString("DuplicateCfdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar un correo..
        /// </summary>
        internal static string ErrorSendingMail {
            get {
                return ResourceManager.GetString("ErrorSendingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar el elemento..
        /// </summary>
        internal static string FailedToFindItem {
            get {
                return ResourceManager.GetString("FailedToFindItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos ocurrió un error, favor de esperar un momento e intentar de nuevo..
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El certificado del emisor es inválido..
        /// </summary>
        internal static string InvalidCertificate {
            get {
                return ResourceManager.GetString("InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La estructura del comprobante es incorrecta..
        /// </summary>
        internal static string InvalidCfdiStructure {
            get {
                return ResourceManager.GetString("InvalidCfdiStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El sello digital del comprobante es inválido..
        /// </summary>
        internal static string InvalidDigitalSeal {
            get {
                return ResourceManager.GetString("InvalidDigitalSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La versión del esquema CFDI no es válida o no es soportada..
        /// </summary>
        internal static string InvalidSchemaVersion {
            get {
                return ResourceManager.GetString("InvalidSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El UUID generado es inválido..
        /// </summary>
        internal static string InvalidUuid {
            get {
                return ResourceManager.GetString("InvalidUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comprobante no utiliza la codificación UTF-8 requerida..
        /// </summary>
        internal static string InvalidXmlEncoding {
            get {
                return ResourceManager.GetString("InvalidXmlEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato XML del comprobante no es válido..
        /// </summary>
        internal static string InvalidXmlFormat {
            get {
                return ResourceManager.GetString("InvalidXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el certificado del emisor..
        /// </summary>
        internal static string MissingCertificate {
            get {
                return ResourceManager.GetString("MissingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el sello digital del comprobante..
        /// </summary>
        internal static string MissingDigitalSeal {
            get {
                return ResourceManager.GetString("MissingDigitalSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta uno o más nodos obligatorios en el comprobante..
        /// </summary>
        internal static string MissingRequiredNode {
            get {
                return ResourceManager.GetString("MissingRequiredNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló la autorización con el PAC..
        /// </summary>
        internal static string PacAuthorizationFailed {
            get {
                return ResourceManager.GetString("PacAuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comprobante no cumple con el esquema XSD del SAT..
        /// </summary>
        internal static string SchemaValidationFailed {
            get {
                return ResourceManager.GetString("SchemaValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El sello digital no corresponde al certificado utilizado..
        /// </summary>
        internal static string SealMismatch {
            get {
                return ResourceManager.GetString("SealMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio de timbrado no se encuentra disponible..
        /// </summary>
        internal static string TimbradoServiceUnavailable {
            get {
                return ResourceManager.GetString("TimbradoServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tiempo de espera para el timbrado fue excedido..
        /// </summary>
        internal static string TimbradoTimeout {
            get {
                return ResourceManager.GetString("TimbradoTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no autentificado.
        /// </summary>
        internal static string UserNoAuthenticate {
            get {
                return ResourceManager.GetString("UserNoAuthenticate", resourceCulture);
            }
        }
    }
}
